# Generated by Django 5.1.3 on 2025-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Manufacturer', models.CharField(blank=True, max_length=25, null=True)),
                ('Store', models.CharField(blank=True, max_length=25, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('watt', models.PositiveIntegerField(blank=True, null=True)),
                ('PD', models.BooleanField(blank=True, null=True)),
                ('thunderbolt', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
