# Generated by Django 5.1.3 on 2025-01-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像'),
        ),
    ]
